Update BuildTimeout.yml

diff --git a/.github/workflows/BuildTimeout.yml b/.github/workflows/BuildTimeout.yml
--- a/.github/workflows/BuildTimeout.yml
+++ b/.github/workflows/BuildTimeout.yml
@@ -13,4 +13,13 @@ jobs:
       with:
          timeout_seconds: 16
          max_attempts: 3
-         command: timeout -s 15 ls
+         command: |
+          max_retry=3
+          counter=0
+          until ls -la
+          do
+            sleep 1
+            [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
+            echo "Trying again. Try #$counter"
+            ((counter++))
+          done
